---
version: "3.8"
services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    volumes:
      - /opt/minecraft:/data
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      MEMORY: 2G
    tty: TRUE
    stdin_open: TRUE
    privileged: TRUE
    restart: "no"