#! /bin/sh
#
# This script should be called by upssched via the CMDSCRIPT directive.
#
# Here is a quick example to show how to handle a bunch of possible
# timer names with the help of the case structure.
#
# This script may be replaced with another program without harm.
#
# The first argument passed to your CMDSCRIPT is the name of the timer
# from your AT lines.

logger -t upssched-cmd "Calling upssched-cmd $1"

case $1 in
        emailonbatt)
                {
                        echo From: upsmon.local.lan
                        echo To: edward.ingram23@gmail.com
                        echo Subject: UPSMON Alert - ONBATTERY
                        echo
                        echo Power loss - Using battery power.
                }  | sendmail -t
                ;;
        startshutdown)
                {
                        echo From: upsmon.local.lan
                        echo To: edward.ingram23@gmail.com
                        echo Subject: UPSMON Alert - SHUTDOWN STARTING
                        echo
                        echo Shutting down VMs and ESXi hosts
                }  | sendmail -t
                export HOME=/home/nutmon
                pwsh /home/nutmon/vmware-shutdown.ps1
                ;;
        emailonline)
                {
                        echo From: upsmon.local.lan
                        echo To: edward.ingram23@gmail.com
                        echo Subject: UPSMON Alert - POWER BACK ONLINE
                        echo
                        echo Power restored
                }  | sendmail -t
                ;;
        *)
                logger -t upssched-cmd "Unrecognized command: $1"
                ;;
esac